image: jelaniwoods/appdev2021-photogram-final@sha256:fc0c8194927907b0e89fd77c8ea9e576051db67af272b82ce50bcdf9364b9da5

tasks:
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced@0.5.1:s3vD5qiY6/HbtRrgDlbMiQ==
    - vortizhe.simple-ruby-erb@0.2.1:BzpDuNAqJwUkxqT2t1YIuQ==
    - CraigMaslowski.erb@0.0.1:5znDha/nn0PphUrpB9a5Nw==
    - Vense.rails-snippets@0.5.0:w1Rd4bmOp7tM7xc3UJruRQ==
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
    - aliariff.vscode-erb-beautify@0.2.0:JPBIiJcuf3dj5jx4nE7u8Q==
    - mbessey.vscode-rufo@0.2.1:QlBwvnvHJPqtDjkgo7+OEQ==
